on:
  push:
    branches:
      - master
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: anagram
      - uses: reznikmm/fedora-ada-action@master
        with:
          spec: anagram/packages/travis/anagram.spec
